### ISSUE TITLE
RTSP traffic

### ISSUE THREAD

**Issue by x-jokay** [containous/traefik-library-image#50]
Hellu

Is it possible to route RTSP traffic using traefik somehow?

e.g.

```toml
[entryPoints]

  [entryPoints.rtsp]
  address = ":4231"

[file]
watch = true

  [frontends] 
    [frontends.cam-1]
    entryPoints = ["rtsp"]
    backend = "cam-1"
    passHostHeader = true
      [frontends.cam-1.routes.root]
      rule = "Host:cam-1.tempuri.org"

  [backends]
    [backends.cam-1]
      [backends.cam-1.loadbalancer.stickiness]
      [backends.cam-1.servers]
        [backends.cam-1.servers.root]
        url = "rtsp://myuser:mypassword@192.168.123.25:4231/cam/realmonitor?channel=1&subtype=0"
```
